import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import * as React from "react";
import { ColonyCounterPage } from "@/routes/tools/colony-counter";
import { ColonyDemoPlates, DEMO_PLATES } from "../ColonyDemoPlates";
import { ColonyWorkflowGuide } from "../ColonyWorkflowGuide";
import { CfuCalculator } from "../CfuCalculator";
import { ColonyExportActions } from "../ColonyExportActions";
import * as apiModule from "@/lib/colony-api";
import * as demoModule from "../ColonyDemoPlates";

// Mock router to render the full ColonyCounterPage in testing environment
vi.mock("@tanstack/react-router", () => ({
  createFileRoute: () => (config: any) => config,
  Link: ({ children }: any) => children,
  useLocation: () => ({ pathname: "/tools/colony-counter" }),
}));

// Mock ColonyDetectionCanvas and ColonyPrintReport to keep tests focused on explanation and layout
vi.mock("@/components/tools/ColonyDetectionCanvas", () => ({
  ColonyDetectionCanvas: () => <div data-testid="mock-detection-canvas" />,
}));
vi.mock("@/components/tools/ColonyPrintReport", () => ({
  ColonyPrintReport: () => <div data-testid="mock-print-report" />,
}));

// Mock SiteHeader & SiteFooter
vi.mock("@/components/site-header", () => ({
  SiteHeader: () => <header data-testid="mock-site-header" />,
}));
vi.mock("@/components/site-footer", () => ({
  SiteFooter: () => <footer data-testid="mock-site-footer" />,
}));

// Mock object URLs
global.URL.createObjectURL = vi.fn(() => "blob:mock-url");
global.URL.revokeObjectURL = vi.fn();

describe("Colony Counter Product & Demo Explanation UX", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  // 1. Product introduction renders with factual description
  it("renders product introduction with required title and factual description without unsupported claims", () => {
    render(<ColonyCounterPage />);

    // Primary heading
    const title = screen.getByRole("heading", { level: 1, name: "AI Petri Dish Colony Counter" });
    expect(title).toBeInTheDocument();

    // Short factual description
    expect(
      screen.getByText(
        "Upload a Petri dish image to detect colonies, review the detections, calculate CFU/mL, and export the analysis.",
      ),
    ).toBeInTheDocument();

    // Verify absence of unsupported accuracy/validation claims
    const pageText = document.body.textContent || "";
    expect(pageText).not.toMatch(/100% accuracy/i);
    expect(pageText).not.toMatch(/clinical accuracy/i);
    expect(pageText).not.toMatch(/laboratory validation/i);
    expect(pageText).not.toMatch(/scientific certification/i);
    expect(pageText).not.toMatch(/replacement for laboratory personnel/i);
    expect(pageText).not.toMatch(/AI guarantees/i);
  });

  // 2. Demo section clearly communicates that demo plates are available
  it("clearly communicates demo plate availability to first-time users", () => {
    render(<ColonyCounterPage />);

    // In demo section
    expect(screen.getByText("No Petri dish image? Try a demo plate.")).toBeInTheDocument();

    // In upload section
    expect(screen.getByText("No Petri dish image? Try a demo plate below.")).toBeInTheDocument();
  });

  // 3. Existing Demo Plate A/B/C remain available
  it("retains existing Demo Plate A, B, and C with density labels", () => {
    render(<ColonyCounterPage />);

    expect(screen.getByText("Demo Plate A — Low Density")).toBeInTheDocument();
    expect(screen.getByText("Demo Plate B — Medium Density")).toBeInTheDocument();
    expect(screen.getByText("Demo Plate C — High Density")).toBeInTheDocument();

    expect(screen.getByText("Low Density")).toBeInTheDocument();
    expect(screen.getByText("Medium Density")).toBeInTheDocument();
    expect(screen.getByText("High Density")).toBeInTheDocument();

    expect(screen.getByRole("button", { name: "Use Demo Plate A — Low Density" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Use Demo Plate B — Medium Density" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Use Demo Plate C — High Density" })).toBeInTheDocument();
  });

  // 4. Synthetic/demo disclaimer remains visible and accessible
  it("displays synthetic demo disclaimer without claiming ground truth", () => {
    render(<ColonyDemoPlates onSelectDemo={vi.fn()} />);

    const disclaimer = screen.getByText(/Demo plates are synthetic examples for exploring the interface/);
    expect(disclaimer).toBeInTheDocument();
    expect(disclaimer).toHaveTextContent(
      "Results are generated by the same analysis workflow used for uploaded images",
    );
    expect(disclaimer).toHaveTextContent(
      "Demo images are provided for software demonstration only and are not real specimen results",
    );
  });

  // 5. Existing guided workflow remains the single workflow explanation
  it("renders existing guided workflow as the single workflow explanation with required step copy", () => {
    render(<ColonyWorkflowGuide pageState="EMPTY" selectedFile={null} />);

    // Exactly 5 steps
    const steps = screen.getAllByRole("listitem");
    expect(steps.length).toBe(5);

    // Exact required step purpose descriptions
    expect(screen.getByText("Upload an image or choose a demo plate.")).toBeInTheDocument();
    expect(screen.getByText("Run AI colony detection.")).toBeInTheDocument();
    expect(screen.getByText("Review, remove, or add detections.")).toBeInTheDocument();
    expect(screen.getByText("Use the selected colony count for CFU/mL calculation.")).toBeInTheDocument();
    expect(screen.getByText("Export detection and analysis results.")).toBeInTheDocument();
  });

  // 6. Post-analysis explanation is displayed in the appropriate area
  it("explains what happens after Analyze near the analyze area without unsupported claims", () => {
    render(<ColonyCounterPage />);

    const postAnalyzeExplanation = screen.getByTestId("post-analyze-explanation");
    expect(postAnalyzeExplanation).toBeInTheDocument();
    expect(postAnalyzeExplanation).toHaveTextContent("What happens after Analyze?");
    expect(postAnalyzeExplanation).toHaveTextContent(
      "After analysis, detected colonies are shown on the plate. You can review the detections, remove false detections, add missed colonies, and use the reviewed count for downstream calculations.",
    );

    // Ensure it does NOT make exaggerated claims
    expect(postAnalyzeExplanation.textContent).not.toMatch(/finds every colony/i);
    expect(postAnalyzeExplanation.textContent).not.toMatch(/guarantees the count/i);
    expect(postAnalyzeExplanation.textContent).not.toMatch(/validates the plate/i);
  });

  // 7. Human-review explanation distinguishes AI detections, human review, and reviewed count
  it("explains human review and provenance transparently", () => {
    render(<ColonyCounterPage />);

    const overviewCard = screen.getByTestId("product-overview-card");
    expect(overviewCard).toBeInTheDocument();

    // AI detections description
    expect(overviewCard).toHaveTextContent("Colonies detected automatically from the image");

    // Human review description
    expect(overviewCard).toHaveTextContent(
      "Review the detections and remove or add colonies when needed. Detections can be reviewed and manually adjusted before using the reviewed count.",
    );

    // Quantify & Export description
    expect(overviewCard).toHaveTextContent(
      "Calculate CFU/mL using the reviewed count, then export summary CSV, detection coordinates, or printable PDF lab documentation.",
    );
  });

  // 8. CFU explanation references selected colony count without duplicating calculation logic
  it("renders CFU/mL explanation referencing selected count without modifying calculation logic", () => {
    render(<CfuCalculator aiCount={120} reviewedCount={115} hasModifications={true} />);

    expect(
      screen.getByText(
        "CFU/mL is calculated from the selected colony count, sample volume, and dilution factor.",
      ),
    ).toBeInTheDocument();
  });

  // 9. Export explanation is present in export panel
  it("renders export explanation for record keeping in ColonyExportActions", () => {
    const mockResponse: apiModule.ColonyDetectionSuccessResponse = {
      success: true,
      count: 42,
      detections: [],
      annotated_image_url: "/annotated.jpg",
      image: { width: 500, height: 500 },
      processing_time_ms: 100,
    };

    render(
      <ColonyExportActions
        filename="plate.jpg"
        response={mockResponse}
        appliedThreshold={0.3}
        reviewedCount={42}
        removedCount={0}
        addedCount={0}
      />,
    );

    expect(
      screen.getByText("Export the reviewed results and analysis report for record keeping."),
    ).toBeInTheDocument();
  });

  // 10. No duplicate workflow/result/calculator/export controls are introduced
  it("avoids duplicate workflow steppers, overview banners, or duplicate controls", () => {
    render(<ColonyCounterPage />);

    // Single workflow navigation
    const workflowNav = screen.getAllByRole("navigation", { name: "Workflow Stages" });
    expect(workflowNav.length).toBe(1);

    // Single product overview card
    const overviewCards = screen.getAllByTestId("product-overview-card");
    expect(overviewCards.length).toBe(1);

    // Single confidence slider
    const sliders = screen.getAllByRole("slider", { name: "Confidence threshold slider" });
    expect(sliders.length).toBe(1);
  });

  // 11. Accessibility semantics remain correct
  it("maintains correct semantic structure, landmarks, and accessible names", () => {
    render(<ColonyCounterPage />);

    // Main landmark
    expect(screen.getByRole("main")).toBeInTheDocument();

    // Live status region
    const statusRegion = screen.getByRole("status");
    expect(statusRegion).toHaveAttribute("aria-live", "polite");

    // All demo buttons have descriptive accessible names
    DEMO_PLATES.forEach((demo) => {
      expect(screen.getByRole("button", { name: `Use ${demo.name}` })).toBeInTheDocument();
    });
  });

  // 12. End-to-end demo plate selection and inference flow explanation
  it("loads demo plate, displays ready-state explanation, and proceeds to analysis", async () => {
    const mockDemoFile = new File(["fake image content"], "demo-plate-a-low-density.jpg", {
      type: "image/jpeg",
    });
    vi.spyOn(demoModule, "fetchDemoPlateFile").mockResolvedValue(mockDemoFile);
    vi.spyOn(apiModule, "detectColonies").mockResolvedValue({
      success: true,
      count: 28,
      detections: [
        { x1: 10, y1: 10, x2: 25, y2: 25, confidence: 0.92, class_id: 0, class_name: "colony" },
      ],
      annotated_image_url: "/outputs/annotated_demo_a.jpg",
      image: { width: 640, height: 640 },
      processing_time_ms: 120,
      quality: {
        density_level: "low",
        confluence_risk: "low",
        review_recommended: false,
        overlap_ratio: 0.01,
        reason: "Low density plate.",
      },
    });

    render(<ColonyCounterPage />);

    // Initially in EMPTY state
    expect(screen.getByText("No Specimen Selected")).toBeInTheDocument();
    expect(
      screen.getByText(
        "Upload a culture plate image or choose a demo plate to begin automated colony counting.",
      ),
    ).toBeInTheDocument();

    // Select Demo Plate A
    const demoBtn = screen.getByRole("button", { name: "Use Demo Plate A — Low Density" });
    fireEvent.click(demoBtn);

    await waitFor(() => {
      expect(screen.getByText("Ready for Analysis")).toBeInTheDocument();
    });

    // Check ready-state post-analysis explanation
    expect(
      screen.getByText(/Click 'Analyze Petri Dish' to run colony detection\. After analysis, detected colonies are shown on the plate\./),
    ).toBeInTheDocument();

    // Trigger Analyze
    const analyzeBtn = screen.getByRole("button", { name: /Analyze Petri dish plate/i });
    fireEvent.click(analyzeBtn);

    await waitFor(() => {
      expect(screen.getByText("Detection & Review Canvas")).toBeInTheDocument();
    });

    // Human review explanation on the canvas
    expect(
      screen.getByText(
        /Review the detections and remove or add colonies when needed\. AI detections: Colonies detected automatically from the image\. Reviewed count: The count after the available review changes\./,
      ),
    ).toBeInTheDocument();
  });
});
