/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardMentorsRouteImport } from './routes/dashboard/mentors'
import { Route as DashboardGuidanceRouteImport } from './routes/dashboard/guidance'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGuidanceRouteImport } from './routes/admin/guidance'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as DashboardEnrollCourseIdRouteImport } from './routes/dashboard/enroll.$courseId'
import { Route as DashboardBookMentorIdRouteImport } from './routes/dashboard/book.$mentorId'
import { Route as AdminCoursesNewRouteImport } from './routes/admin/courses/new'
import { Route as AdminCoursesCourseIdPreviewRouteImport } from './routes/admin/courses/$courseId.preview'
import { Route as AdminCoursesCourseIdEditRouteImport } from './routes/admin/courses/$courseId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorsRoute = DashboardMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuidanceRoute = DashboardGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidanceRoute = AdminGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const DashboardEnrollCourseIdRoute = DashboardEnrollCourseIdRouteImport.update({
  id: '/enroll/$courseId',
  path: '/enroll/$courseId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookMentorIdRoute = DashboardBookMentorIdRouteImport.update({
  id: '/book/$mentorId',
  path: '/book/$mentorId',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesCourseIdPreviewRoute =
  AdminCoursesCourseIdPreviewRouteImport.update({
    id: '/$courseId/preview',
    path: '/$courseId/preview',
    getParentRoute: () => AdminCoursesRoute,
  } as any)
const AdminCoursesCourseIdEditRoute =
  AdminCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => AdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/dashboard/book/$mentorId': typeof DashboardBookMentorIdRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/courses/$courseId/preview': typeof AdminCoursesCourseIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/dashboard/book/$mentorId': typeof DashboardBookMentorIdRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/courses/$courseId/preview': typeof AdminCoursesCourseIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/dashboard/book/$mentorId': typeof DashboardBookMentorIdRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/courses/$courseId/edit': typeof AdminCoursesCourseIdEditRoute
  '/admin/courses/$courseId/preview': typeof AdminCoursesCourseIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/projects/$slug'
    | '/blog/'
    | '/courses/'
    | '/dashboard/'
    | '/projects/'
    | '/admin/courses/new'
    | '/dashboard/book/$mentorId'
    | '/dashboard/enroll/$courseId'
    | '/admin/courses/'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/blogs'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/projects/$slug'
    | '/blog'
    | '/courses'
    | '/dashboard'
    | '/projects'
    | '/admin/courses/new'
    | '/dashboard/book/$mentorId'
    | '/dashboard/enroll/$courseId'
    | '/admin/courses'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/preview'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/projects/$slug'
    | '/blog/'
    | '/courses/'
    | '/dashboard/'
    | '/projects/'
    | '/admin/courses/new'
    | '/dashboard/book/$mentorId'
    | '/dashboard/enroll/$courseId'
    | '/admin/courses/'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  EmployeesRoute: typeof EmployeesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentors': {
      id: '/dashboard/mentors'
      path: '/mentors'
      fullPath: '/dashboard/mentors'
      preLoaderRoute: typeof DashboardMentorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guidance': {
      id: '/dashboard/guidance'
      path: '/guidance'
      fullPath: '/dashboard/guidance'
      preLoaderRoute: typeof DashboardGuidanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guidance': {
      id: '/admin/guidance'
      path: '/guidance'
      fullPath: '/admin/guidance'
      preLoaderRoute: typeof AdminGuidanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/dashboard/enroll/$courseId': {
      id: '/dashboard/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/dashboard/enroll/$courseId'
      preLoaderRoute: typeof DashboardEnrollCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/book/$mentorId': {
      id: '/dashboard/book/$mentorId'
      path: '/book/$mentorId'
      fullPath: '/dashboard/book/$mentorId'
      preLoaderRoute: typeof DashboardBookMentorIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$courseId/preview': {
      id: '/admin/courses/$courseId/preview'
      path: '/$courseId/preview'
      fullPath: '/admin/courses/$courseId/preview'
      preLoaderRoute: typeof AdminCoursesCourseIdPreviewRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$courseId/edit': {
      id: '/admin/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof AdminCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminCoursesCourseIdEditRoute: typeof AdminCoursesCourseIdEditRoute
  AdminCoursesCourseIdPreviewRoute: typeof AdminCoursesCourseIdPreviewRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminCoursesCourseIdEditRoute: AdminCoursesCourseIdEditRoute,
  AdminCoursesCourseIdPreviewRoute: AdminCoursesCourseIdPreviewRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminGuidanceRoute: typeof AdminGuidanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminGuidanceRoute: AdminGuidanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardGuidanceRoute: typeof DashboardGuidanceRoute
  DashboardMentorsRoute: typeof DashboardMentorsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBookMentorIdRoute: typeof DashboardBookMentorIdRoute
  DashboardEnrollCourseIdRoute: typeof DashboardEnrollCourseIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardGuidanceRoute: DashboardGuidanceRoute,
  DashboardMentorsRoute: DashboardMentorsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBookMentorIdRoute: DashboardBookMentorIdRoute,
  DashboardEnrollCourseIdRoute: DashboardEnrollCourseIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  EmployeesRoute: EmployeesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
