/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard/payments'
import { Route as DashboardMentorsRouteImport } from './routes/dashboard/mentors'
import { Route as DashboardGuidanceRouteImport } from './routes/dashboard/guidance'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGuidanceRouteImport } from './routes/admin/guidance'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as DashboardEnrollCourseIdRouteImport } from './routes/dashboard/enroll.$courseId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorsRoute = DashboardMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuidanceRoute = DashboardGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidanceRoute = AdminGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardEnrollCourseIdRoute = DashboardEnrollCourseIdRouteImport.update({
  id: '/enroll/$courseId',
  path: '/enroll/$courseId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/employees': typeof EmployeesRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/signup': typeof SignupRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/guidance': typeof AdminGuidanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/guidance': typeof DashboardGuidanceRoute
  '/dashboard/mentors': typeof DashboardMentorsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/enroll/$courseId': typeof DashboardEnrollCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/auth/callback'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/enroll/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/auth/callback'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/enroll/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/disclaimer'
    | '/employees'
    | '/login'
    | '/onboarding'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/signup'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/enrollments'
    | '/admin/guidance'
    | '/admin/login'
    | '/admin/mentors'
    | '/auth/callback'
    | '/dashboard/certificates'
    | '/dashboard/courses'
    | '/dashboard/guidance'
    | '/dashboard/mentors'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/enroll/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  EmployeesRoute: typeof EmployeesRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentors': {
      id: '/dashboard/mentors'
      path: '/mentors'
      fullPath: '/dashboard/mentors'
      preLoaderRoute: typeof DashboardMentorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guidance': {
      id: '/dashboard/guidance'
      path: '/guidance'
      fullPath: '/dashboard/guidance'
      preLoaderRoute: typeof DashboardGuidanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guidance': {
      id: '/admin/guidance'
      path: '/guidance'
      fullPath: '/admin/guidance'
      preLoaderRoute: typeof AdminGuidanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/enroll/$courseId': {
      id: '/dashboard/enroll/$courseId'
      path: '/enroll/$courseId'
      fullPath: '/dashboard/enroll/$courseId'
      preLoaderRoute: typeof DashboardEnrollCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminGuidanceRoute: typeof AdminGuidanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminGuidanceRoute: AdminGuidanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardGuidanceRoute: typeof DashboardGuidanceRoute
  DashboardMentorsRoute: typeof DashboardMentorsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEnrollCourseIdRoute: typeof DashboardEnrollCourseIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardGuidanceRoute: DashboardGuidanceRoute,
  DashboardMentorsRoute: DashboardMentorsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEnrollCourseIdRoute: DashboardEnrollCourseIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  EmployeesRoute: EmployeesRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
